import { PERSONAL_SKILLS_LIST } from '../../actionTypes';

const PERSONAL_SKILLS_LIST_REQUEST = `${PERSONAL_SKILLS_LIST}_REQUEST`
const PERSONAL_SKILLS_LIST_SUCCESS = `${PERSONAL_SKILLS_LIST}_SUCCESS`
const PERSONAL_SKILLS_LIST_ERROR = `${PERSONAL_SKILLS_LIST}_ERROR`

export {
  PERSONAL_SKILLS_LIST_REQUEST,
  PERSONAL_SKILLS_LIST_SUCCESS,
  PERSONAL_SKILLS_LIST_ERROR
}